name: pull request
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          cp dist/index.html dist/404.html
